parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        dbname: %env(DATABASE_DB)%
        host: %env(DATABASE_HOST)%
        port: %env(DATABASE_PORT)%
        user: %env(DATABASE_USER)%
        password: %env(DATABASE_PASSWORD)%
        driver: pdo_pgsql
        charset: utf8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
