security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        db_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/
            http_basic: ~
            provider: db_user_provider
            logout_on_user_change: true
        main:
            pattern: ^/
            http_basic: ~
            logout_on_user_change: true
            provider: db_user_provider

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 15

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
